language: node_js
node_js:
- 5.7.0
sudo: required
services:
- docker
script:
- docker-compose -f docker-compose-test.yml build
- docker-compose -f docker-compose-test.yml run test
env:
  global:
  - secure: M+NxSbTj/6Nsiia3lAbaVgvL+D+Pqq05CiM65NvyI0Z11Uv9O0c3cfZWxX03MprxbH5gIoBg3qOeocRXDxYtfTBp0JpXHMgxd5CZ4UUvT15/8mwAY6HoPuV46M+g8Xxs+JdyPjuy9s5Pqe+1CXDReIwzdCUF6Q9eYnPK5kcVDyUN1OwsaOylnhSBwUQowTB/wgNTT1qVtehEuJMns6z+x17WOPVF0lA8vYt1xQ5tZ5gNCS8hofjHr5JDUwm0bU8KeKa804rcaxa4PqyKd2vqzrdGgs/HWC4ZXQ0ITLYy2gl+GAFnFgPdHjAFpaH+RTlfQyptDjhBk1pIUQew8K1ax2WLwyNbGjDiRLwD+Cq4dfimvdN278fercg7GNvVEX/f2PECXzkCWqhK3r99HzOCDOJAbkTrnq/VxADm2uEHtbQb1sEOlwHLN2Aj7eJgdXFZgTtE91I1ABsQPa9xWtGYKyBICdozfrKf0VoriMxwG/XhH4kIwbx69qG0dbvFaIhcx19nx/FaiFEhJt01czVJjDy8CFMAhLtzHSgIQ9dDAuo8Qqa/SA7ZCPpPiensnpef3B5bo5ECZQ49Q8dBqdNYpZJZA5eIN0hwh2bbYSge2fZhEcwd0vz/V0c7m6t3L85JCRgzoGNVHT4Y4JZeERh7xAj5KVXimB4bOGPNiu4TJR4=
  - secure: AybyjeFGAfOSZMTNFOBYXjgAGxibaonby5GrXTVQ3NAAFK5CwJXQo/Xn8TGos4csjg9sdT8QweIdish327sO9JOvfHMpmJc+uaacOXkSWUUObxvQJK/1urhhbxpbdwGgEdpIoL+n9fHrNsyv8NePYTo4ZL8NjRIOXHT8RtzvZuP8+Ng49vnGugxl8CIKcG3mDdhK3IkVX83IwraX31bTkwL7KvoCId9I4ODgbtPu9D4sDwzavfuQvGsj+4b04uPi7hDx36Wkk63pfDrxJYa6+YhJo4maBAwfMk00YUN/3Mi8hy5mUn5ZWykvdm6ms9njhJOFBiHbVrITD0NTENyuDLcVWjJ3FwmlaY+mCe2jtULVzyL9KCKn2qRyJfk0eompPTkc3cuv2T1pxTtvbsaAwf8bEsHSJq6CydOx3mrRBRkKlksvCqAMC3OTUBMxrxu231xy3A3MNfGRhvVl/MBs4Vs7f04rhQVUhFV+T+g9PUBG7Dwc+eIeq1WiukwkGkHp+YKk6VQ/17IdUvct0YD9R0JLyTbSh4nuBUMiOIG7OJ21KXGTzbb4SM/QsXsEvi7+DaVhzKPJvq6Nnu1OlToF+21CftOFojEe3vlfV0SvmB7t4lvdVhA7FQbrw/R8Zsve0L5OrglSZt2gHvxxNbdwCUudUHjyKxGKqF7Q8sAv2cM=
before_install:
- bash _scripts/install.sh
after_success:
- bash _scripts/deploy.sh
