prod:
  image: vizzuality/gfw-story-api:1.1.0${STAGING}
  ports:
    - "3500"
  env_file:
    - prod.env
  command: start
  restart: always
  log_driver: "syslog"
  log_opt:
    syslog-address: ${SYSLOG_ADDRESS}
    tag: gfw-story-api${STAGING}

