develop:
  extends:
    file: base.yml
    service: base
  ports:
    - "35736:35729"
  container_name: gfw-story-api-develop
  environment:
    NODE_ENV: dev
    CARTODB_APIKEY: <key>
    CARTODB_USER: <user>
    QUEUE_URL: redis://mymachine:6379
    QUEUE_PROVIDER: redis
    QUEUE_NAME: mail
    CT_URL: http://mymachine:9000
    LOCAL_URL: http://mymachine:3500
    CT_TOKEN: <token>
    WRI_MAIL_RECIPIENTS: <emails>
    CT_REGISTER_MODE: auto
  command: develop
  links:
    - mongo
  volumes:
    - ./app:/opt/gfw-story-api/app
mongo:
  extends:
    file: base.yml
    service: mongo
