version: "3"
services:
  develop:
    build: .
    ports:
      - "3500:3500"
    container_name: gfw-story-api
    environment:
      PORT: 3500
      NODE_PATH: app/src
      NODE_ENV: dev
      CARTODB_APIKEY: <key>
      CARTODB_USER: <user>
      QUEUE_URL: redis://mymachine:6379
      QUEUE_NAME: mail
      CT_URL: http://mymachine:9000
      LOCAL_URL: http://mymachine:3500
      CT_TOKEN: <token>
      WRI_MAIL_RECIPIENTS: <emails>
      CT_REGISTER_MODE: auto
    command: develop
    links:
      - mongo
    volumes:
      - ./app:/opt/gfw-story-api/app

  mongo:
    image: mongo
    container_name: gfw-story-mongo
    command: --smallfiles
    ports:
      - "27017"
    volumes:
      # in osx the host machine volume directory cannot be under /Users
      # http://stackoverflow.hex1.ru/questions/34390220/how-to-mount-external-volume-for-mongodb-using-docker-compose-and-docker-machine
      - $HOME/docker/data/gfw-story-api:/data/db
    restart: always
