develop:
  extends:
    file: base.yml
    service: base
  ports:
    - "35736:35729"
  container_name: gfw-story-api-develop
  environment:
    NODE_ENV: dev
    CARTODB_APIKEY: <apikey>
    CARTODB_USER: <user>
    QUEUE_URL: redis://192.168.99.100:6379
    QUEUE_PROVIDER: redis
  command: develop
  links:
    - mongo
  volumes:
    - ./app:/opt/gfw-story-api/app
mongo:
  extends:
    file: base.yml
    service: mongo
