prod:
  image: vizzuality/gfw-story-api:1.1.0${STAGING}
  ports:
    - "3500"
  env_file:
    - prod.env
  command: start
  restart: always
  log_driver: "gelf"
  log_opt:
    gelf-address: ${GELF_ADDRESS}
