version: "3"
services:
  test:
    build: .
    ports:
      - "3500"
    container_name: gfw-story-api-test
    environment:
      PORT: 3500
      NODE_PATH: app/src
      NODE_ENV: test
      MONGO_PORT_27017_TCP_ADDR: mongo
      QUEUE_URL: redis://redis:6379
      GATEWAY_URL: http://mymachine:9000
      WAIT_HOSTS: redis:6379, mongo:27017
      FASTLY_ENABLED: "false"
      LOCAL_URL: http://mymachine:3055
      MICROSERVICE_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
    command: test
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:3.4
    command: --smallfiles
    ports:
      - "27017"

  redis:
    image: redis:5.0.8-alpine3.11
    container_name: redis-test
    ports:
      - "6379"

