apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: story
  name: story
  namespace: gfw
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      name: story
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: story
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - apps
      containers:
        - args:
            - start
          env:
            - name: PORT
              value: "3500"
            - name: NODE_ENV
              value: prod
            - name: NODE_PATH
              value: app/src
            - name: LOCAL_URL
              value: http://story.gfw.svc.cluster.local:3500
            - name: QUEUE_NAME
              value: mail_prod
            - name: WRI_MAIL_RECIPIENTS
              value: teresa.schofield@wri.org,alice.gottesman@wri.org,abarrett@wri.org
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  key: STORY_MONGO_URI
                  name: dbsecrets
            - name: QUEUE_URL
              valueFrom:
                secretKeyRef:
                  key: REDIS_URI
                  name: dbsecrets
            - name: NEWRELIC_LICENSE
              valueFrom:
                secretKeyRef:
                  key: NEWRELIC_LICENSE
                  name: mssecrets
            - name: GATEWAY_URL
              valueFrom:
                secretKeyRef:
                  key: GATEWAY_URL
                  name: mssecrets
            - name: CARTODB_USER
              valueFrom:
                secretKeyRef:
                  key: CARTODB_USER
                  name: mssecrets
            - name: CARTODB_APIKEY
              valueFrom:
                secretKeyRef:
                  key: CARTODB_APIKEY
                  name: mssecrets
            - name: FASTLY_ENABLED
              valueFrom:
                secretKeyRef:
                  key: FASTLY_ENABLED
                  name: mssecrets
            - name: FASTLY_APIKEY
              valueFrom:
                secretKeyRef:
                  key: FASTLY_APIKEY
                  name: mssecrets
                  optional: true
            - name: FASTLY_SERVICEID
              valueFrom:
                secretKeyRef:
                  key: FASTLY_SERVICEID
                  name: mssecrets
                  optional: true
          image: gfwdockerhub/story
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthcheck
              port: 3500
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 5
          name: story
          ports:
            - containerPort: 3500
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthcheck
              port: 3500
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              cpu: "1"
              memory: 512M
            requests:
              cpu: 250m
              memory: 256M
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
